### ISSUE TITLE
Update dependency management with Go modules

### ISSUE THREAD

**Issue by koletyst** [wave-k8s/wave#102]
Current contribution guideline:
```
(...)
Dependencies are **not** checked in so please download those separately.
Download the dependencies using [`dep`](https://github.com/golang/dep).
```
`dep` is deprecated.

### TODO

- [ ] Replace `dep` uses in codebase with [Go modules](https://golang.org/ref/mod)
- [ ] Test changes
- [ ] Update contribution guideline

**Comment by toelke** [comment]
Fixed with #145
