### ISSUE TITLE
helm installation instructions don't work

### ISSUE THREAD

**Issue by tpo** [wave-k8s/wave#122]
This doesn't work:

> ```
> $ helm repo add wave-k8s https://wave-k8s.github.io/wave/
> $ helm install wave-k8s/wave
> ```

```
$ helm repo add wave-k8s https://wave-k8s.github.io/wave/
"wave-k8s" has been added to your repositories
$ helm install wave-k8s/wave
Error: INSTALLATION FAILED: must either provide a name or specify --generate-name

$ helm version
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

**Comment by tpo** [comment]
> You forgot to set a name for your installation
> 
> `helm install wave wave-k8s/wave -n wave-system`

Yes, or use `--generate-name`. My suggestion is to add `--generate-name` to the documentantion, so that the project has working install instructions in the README.

**Comment by mwmahlberg** [comment]
@tpo That is not wave-specific. It is [basic helm usage](https://helm.sh/docs/helm/helm_install/). However, that PR should be easy enough.

**Comment by AlexsJones** [comment]
```
❯ helm install wave wave-k8s/wave -n wave-system
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/alexjones/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/alexjones/.kube/config
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "wave-wave" namespace: "" from "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "wave-wave" namespace: "" from "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first]
```

What am I doing wrong ?

**Comment by tpo** [comment]
@AlexsJones I'd suggest to open a new ticket. I think this is not the same problem as the origial one in this thicket.

**Comment by Routhinator** [comment]
Looks like we have to apply the CRDs ourselves as part of the installation, however it's not mentioned clearly that the helm chart won't install these.. which is a bit confusing as I would hope most people are using RBAC these days and expect these to be a part of the helm chart.

**Comment by Routhinator** [comment]
Not stale, just not actioned. This is still a problem.

**Comment by Routhinator** [comment]
@github-actions this was not completed. This is still a problem and helm installation does not work.
