### ISSUE TITLE
v1beta1 resource not available change to v1 to make crds work on helm install 

### ISSUE THREAD

**Issue by tux2cool** [wave-k8s/wave#129]
https://github.com/wave-k8s/wave/blob/c3bdcfe923debc572bec313c84e457d2e592af16/charts/wave/templates/clusterrole.yaml#L2

**Comment by cforeman1992** [comment]
clusterrolebindings.yaml has the same issue.

**Comment by MatthiasWerning** [comment]
Having the same issue as well. Creating an own helm chart should work, but seeing this in the official version would be great.

**Comment by tux2cool** [comment]
#130

**Comment by sdc395** [comment]
The PR looks good.  Any chance of it being merged soon?

**Comment by tux2cool** [comment]
Hopefully

**Comment by sdc395** [comment]
Hmm, looks like I'll be replacing Wave with Stakater's Reloader.

**Comment by toelke** [comment]
I merged #112 to fix this.
