### ISSUE TITLE
non-rolling update, i.e. kill pod before starting new

### ISSUE THREAD

**Issue by jgm-ktg** [wave-k8s/wave#131]
I have a pod that depends on a non-sharable volume.

Wave starts a new pod which never comes up because of this.

I'd like an annotation where the deployment is marked for a non-rolling update.

Possible?  New feature?

**Comment by jabdoa2** [comment]
This is something you can configure on your statefulset/daemonset/deployment via `Strategy`. See: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
