### ISSUE TITLE
Can't deploy helm chart on k8s version >v1.22

### ISSUE THREAD

**Issue by acm-073** [wave-k8s/wave#133]
Hello,

the wave helm chart (latest published version is 2.0.0) uses the deprecated API `rbac.authorization.k8s.io/v1beta1` for the ClusterRole and ClusterRoleBinding objects. This API is not served anymore on kubernetes versions 1.22 and above, so it's not possible to deploy wave with the helm chart on these clusters.

Since there are no notable changes between `rbac.authorization.k8s.io/v1beta1` and `rbac.authorization.k8s.io/v1`, the only thing that needs to be changed is the actual API version.

It would be great if we could get an updated chart published some time soon.

Thanks!

**Comment by uwebartels** [comment]
same for me.
Is this project dead?
Updating the helm chart is not too hard, but the Dockerfile is not building either.

`Step 7/15 : RUN dep ensure --vendor-only
 ---> Running in 6aa31cf48f13
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/kubernetes-sigs/kubebuilder: fatal: failed to unpack tree object 29bccabffb065deea1c4cb3273313b615996588a
: exit status 128`

here I am out...

**Comment by acm-073** [comment]
This project seems surely to be dead. I found https://github.com/stakater/Reloader to be a viable alternative.

**Comment by uwebartels** [comment]
nice. thanks.
I'll check it out.

**Comment by toelke** [comment]
I merged #112 to fix this.
