### ISSUE TITLE
Wave Removes StartupProbes

### ISSUE THREAD

**Issue by jan-kantert** [wave-k8s/wave#137]
If you add a `startupProbe` to any deployment/pod with a wave annotation that will be removed by wave. This is probably caused by an old version of the kubernetes API used in wave.

**Comment by starkers** [comment]
Yes; I think you are right

**Comment by toelke** [comment]
This is an understandable duplicate of #118

**Comment by jan-kantert** [comment]
Will be fixed by #145

**Comment by toelke** [comment]
Fixed with #145
