### ISSUE TITLE
New and motivated project member

### ISSUE THREAD

**Issue by toelke** [wave-k8s/wave#138]
Hey all!

This is not an issue, but me reaching out to the rest of the project (such as it is).
@wonderhoss was nice enough to add me to the project after I voiced my wish to contribute.

I am not here to step on anyone's toes, but I am motivated to push this project forward.

This is my preliminary plan:

- merge a number of auto-closed PRs (RBAC, k8s version, some small features) :heavy_check_mark: 
- migrate from `dep` to `go mod` (https://www.cockroachlabs.com/blog/dep-go-modules/)  :heavy_check_mark: 
- update all dependencies
- disable the autoclose-on-stale :heavy_check_mark: (https://github.com/wave-k8s/wave/pull/140) and re-open all issues+PRs closed by it (https://drewdevault.com/2021/10/26/stalebot.html) – as long as they still seem relevant after the previous steps; label open Issues with `FeatureRequest`, `Bug`, …  :heavy_check_mark: 
- Set up some forum for discussing things, e.g. GitHub discussions
- Add some tests, especially end-to-end tests with different Kubernetes versions (https://github.com/wave-k8s/wave/pull/139)  :heavy_check_mark: 

I will start doing these things in the upcoming weeks if nobody complains first 😃 (see stepping on toes).

Cheers,
Philipp

**Comment by jan-kantert** [comment]
Appreciate it! We would be migrating off otherwise since current version does not play well with recent kubernetes versions anymore.

**Comment by mamccorm** [comment]
Hey @toelke - we're 'attempting' to do the migration from 'dep' to go.mod. This is our work so far:
- https://github.com/wave-k8s/wave/compare/master...mamccorm:wave:master

Full disclosure - i'm not a go developer so largely trial and error and piecing bits together. api and webhook build fine, but controller and core do not (yet).

**Comment by toelke** [comment]
Hey.

There is also https://github.com/wave-k8s/wave/pull/105 and https://github.com/wave-k8s/wave/pull/107.

I tested #107. The build works and creates a working binary. The tests fail, however, as the `Makefile` does a lot of `go install / go get` where the sematics have changed or the old versions are no longer available (I found that for `go generate`, for example).

**Comment by toelke** [comment]
Sorry, yes. It's in my queue. Expect a reaction until the weekend.

**Comment by mamccorm** [comment]
Hey @toelke, how's the above going? Does it look any close? :)

**Comment by toelke** [comment]
I replied here: https://github.com/starkers/wave/pull/1#issuecomment-2025929876

**Comment by toelke** [comment]
I'll close this, as initial communication is done.
