### ISSUE TITLE
Upgrade to 4.1 fails

### ISSUE THREAD

**Issue by jabdoa2** [wave-k8s/wave#166]
Upgrade from 4.0 to 4.1 fails:
```
wave   283d   False   Helm upgrade failed for release wave/wave with chart wave@4.1.0: cannot patch "wave-wave" with kind Deployment: Deployment.extensions "wave-wave" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"wave", "heritage":"Helm", "release":"wave"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
Deleting the helm release fixes it.

**Comment by toelke** [comment]
Fixed with #159

**Comment by jabdoa2** [comment]
Previous upgrades worked fine. I guess it was caused be the removal of that annotation. Since wave does not have any state its ok to delete and recreate the release.

Perf-wise the upgrade looks good:
up to 21:00 - 0.5
21:00 - 0.7
10:00 - 0.8

<img width="741" alt="grafik" src="https://github.com/wave-k8s/wave/assets/557540/2ec225eb-7019-4903-b851-97f4a0931472">

<img width="741" alt="grafik" src="https://github.com/wave-k8s/wave/assets/557540/516801b0-7954-45a6-addc-34a3baf7fec3">


This is 1k deployments, 2k configmaps and 6k secrets. So perf-wise it looks very good.

**Comment by toelke** [comment]
I saw that error for the previous updates as well.

**Comment by jabdoa2** [comment]
We will roll out the next stage of clusters next week. I guess it will happen everywhere but it should be good after that.
