### ISSUE TITLE
Allow project specific instead globally on cluster 

### ISSUE THREAD

**Issue by AssafKatz3** [wave-k8s/wave#37]
Hi,
The project currently assume that you want to apply it on cluster global level. While it is good for many cases, this isn't possible in case of enterprise when we aren't the owner of cluster. I suggest to allow to limit the the controller only to one namepsace.
Thanks,

**Comment by JoelSpeed** [comment]
We could potentially add a namespace limitation to the controller or have it check for the presence of a label on the namespace before reconciling it like Kubernetes does for admission controllers.

We will need to have a think about what happens if you have multiple copies of wave running within a namespace, just in case someone deployed one restricted and one unrestricted to a cluster.

@AssafKatz3 Have you tried restricting Wave using RBAC? What happens at present?

**Comment by AssafKatz3** [comment]
Hi,
I tried to use RBAC (default of OpenShift), the software reported on RBAC error (I can regenerate it if it will help you) and do nothing. I am happy with one wave instance per namespace.
Thanks

**Comment by JoelSpeed** [comment]
>  can regenerate it if it will help you

This would be helpful if you have a moment

**Comment by AssafKatz3** [comment]
After:

> I0218 11:59:55.387534       1 main.go:96] entrypoint "level"=0 "msg"="Starting the Cmd."

I see a lot of errors like:

> E0218 11:59:55.390278       1 reflector.go:205] github.com/pusher/wave/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:project-test:default" cannot list configmaps at the cluster scope: User "system:serviceaccount:project-test:default" cannot list all configmaps in the cluster
> ...
> E0218 11:59:55.390392       1 reflector.go:205] github.com/pusher/wave/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:project-test:default" cannot list deployments.apps at the cluster scope: User "system:serviceaccount:project-test:default" cannot list all deployments.apps in the cluster
> ...
> E0218 15:06:13.305193       1 reflector.go:205] github.com/pusher/wave/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:project-test:default" cannot list secrets at the cluster scope: User "system:serviceaccount:project-test:default" cannot list all secrets in the cluster

**Comment by JoelSpeed** [comment]
Ok, so we will need to add `--namespace` flag that handles restricting Wave to a namespace, this should be reasonably easy to do as we only need to pass the restricted namespace to the `manager.New()` call in `cmd/manager/main.go`

**Comment by gargath** [comment]
Even though it's been a while, I still think this would be a valuable addition. Will look into this once the project migration is done.

**Comment by gargath** [comment]
Still relevant

**Comment by AssafKatz3** [comment]
Hi,
I changed job but my new job still requires it...
Thanks

**Comment by gargath** [comment]
It'll go in. I'd like to add a test case, but I'm struggling to find the time at present.
