### ISSUE TITLE
Wave 0.3.0 tries to write logs to /tmp

### ISSUE THREAD

**Issue by voidengineer** [wave-k8s/wave#52]
I recently tried to update to Wave 0.3.0. 
Since I run all pods with a restricted PodSecurityPolicy with a read-only root filesystem, Wave fails with the message:

> cannot create log: open /tmp/wave.wave-1.nobody.log.INFO.*****: read-only file system

With Wave 0.2.0 this did not happen.

**Comment by JoelSpeed** [comment]
@voidengineer Could you please share your configuration for Wave?

No changes have been made to the logging in Wave between v0.2.0 and v0.3.0 that I'm aware of. The only thing that may have introduced this change is an update to the `controller-runtime` dependency or changes to the Dockerfile, though I think the latter is less likely

**Comment by joschi36** [comment]
I noticed another problem. With long-running pods, the node filesystem gets full. For instance, a wave pod running for 34 days produced 18 GB of Logs. The amount of logs was because of an issue on our side, but I think it should never log to the container FS.

**Comment by jabdoa2** [comment]
I can actually confirm that this is still the case. It seems to contain redundant logs. I will have a look at the logger setup.
