### ISSUE TITLE
kustomize vs wave?

### ISSUE THREAD

**Issue by afirth** [wave-k8s/wave#53]
Saw your lightning talk, wondering what this does compared to [kustomize's generator functionality](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configGeneration.md#configmap-generation-and-rolling-updates)? Thanks for speaking!

**Comment by KlavsKlavsen** [comment]
kustomize does not seem to have a way to handle redeploying on secrets changes? I haven't seen how kustomize's configmapGenerator works - it may perform better than this projects approach?
I'm just browsing - and trying to see what way to myself :)

**Comment by gargath** [comment]
The purpose of Wave is to ensure Pods consuming a ConfigMap always run with the current version of that config, regardless of how or why they changed, even at runtime (e.g. by another process).
The ConfigMapGenerator in kustomize runs as part of a kustomization, i.e. at deploy-time (or earlier).

If your deployment flow ensures that each time a ConfigMap is updated all consuming software is also updated, then you may not need Wave at all.
