### ISSUE TITLE
kustomize-referenced RBAC rules do not include DaemonSet and StatefulSet permissions

### ISSUE THREAD

**Issue by JensErat** [wave-k8s/wave#63]
We have two sets of RBAC rules in `conf`:

```bash
$ find . -iname "*role*.yaml"
./config/default/rbac/rbac_role.yaml
./config/default/rbac/rbac_role_binding.yaml
./config/rbac/manager_role.yaml
./config/rbac/manager_role_binding.yaml
```

While `rbac/manager-role.yaml` also contains permissions for `StatefulSets` and `DaemonSets`, those referenced by Kustomize in `default/rbac` do not have them. Looks like they have been forgotten to sync when support for those resources was created?

There is a PR trying to tackle this in #56, but this has not been worked on for more than two months now.

**Comment by gargath** [comment]
Still needs a look.

**Comment by gargath** [comment]
I believe this is resolved. If there is still an issue with the current kustomizations, please re-open.
