### ISSUE TITLE
BinaryData not considered when hashing configmap 

### ISSUE THREAD

**Issue by MikeSchlosser16** [wave-k8s/wave#73]
It looks like https://github.com/pusher/wave/blob/8bddd32d9aa5afcfb1b733df6e9ba520e0689ed4/pkg/core/hash.go#L71 only accounts for `Data` and not `BinaryData`. When changing my configmap with `BinaryData` the hash was always the same and thus the updates not rolled out properly. Logs showed that the hash was updated but it happened to be the same value, so otherwise potentially changing https://github.com/pusher/wave/blob/217c9b8e0797131edbed580aa489db994e4cce45/pkg/core/handler.go#L109 to make this more obvious if there is a reason to not use `binaryData` would make it more obvious. 

If this sounds reasonable I can work on adding a fix. 

Thanks!

**Comment by mcristina422** [comment]
Kubectl utils has functions for hashing `ConfigMaps` and `Secrets`

https://github.com/kubernetes/kubernetes/blob/7aa214d2c3f78598238c761099dacd6ead3d6fcd/staging/src/k8s.io/kubectl/pkg/util/hash/hash.go#L29

**Comment by gargath** [comment]
This is still relevant
