### ISSUE TITLE
Configure wave to only restart pods within a certain time frame

### ISSUE THREAD

**Issue by cgunston** [wave-k8s/wave#80]
Hi all

Firstly thank you for a great tool, we are looking to implement this within our organisation shortly.

However, we did have one main feature request. Would it be possible to only restart a pod within a given time frame? For example only restart pods between 03:00 - 04:00. This would allow us to set restarts to be outside of our core service hours and minimize downtime for our customers.

Thanks
Callum

**Comment by mthssdrbrg** [comment]
I suppose it would be possible to have an annotation that specifies a time frame (I've seen similar approaches in other projects), and have Wave requeue the request until appropriate (or somehow keep track of what needs to be restarted and when).

It's probably do-able but not something that we have the need for currently.
