### ISSUE TITLE
Host helm chart on Github Pages

### ISSUE THREAD

**Issue by Sytten** [wave-k8s/wave#81]
Currently it is not easy to deploy because the helm chart is not published anywhere. A simple way to do it is via github pages. You can see how k8s external secrets do it (https://github.com/godaddy/kubernetes-external-secrets#install-with-helm).

**Comment by Sytten** [comment]
So its easily done with the Github action: https://github.com/helm/chart-releaser-action
In the meantime, I hosted the current chart here: https://github.com/Sytten/helm-charts

**Comment by jgillich** [comment]
I just wondered how I would install it, and it seems like you can't. Thanks for hosting it!

**Comment by Sytten** [comment]
No progress? It would be preferable that the hosting be done by the repository

**Comment by gargath** [comment]
Thank you for your patience. I will be looking into this once the repository migration is complete.

**Comment by Sytten** [comment]
Thanks a lot for taking over the project @gargath 
Much appreciated :)

**Comment by Sytten** [comment]
Relevant

**Comment by gargath** [comment]
This will happen with the next release, hopefully in the next couple of weeks.
Life has unfortunately kept me more busy than I would have liked as of late.

**Comment by Sytten** [comment]
@gargath can you reopen

**Comment by gargath** [comment]
Ah, yeah, I missed this one.

**Comment by gargath** [comment]
Charts are now available via
```
$ helm repo add wave-k8s https://wave-k8s.github.io/wave/
$ helm install wave-k8s/wave
```

Proper documentation to follow.

**Comment by tpo** [comment]
This doesn't work:

> ```
> $ helm repo add wave-k8s https://wave-k8s.github.io/wave/
> $ helm install wave-k8s/wave
> ```

```
$ helm repo add wave-k8s https://wave-k8s.github.io/wave/
"wave-k8s" has been added to your repositories
$ helm install wave-k8s/wave
Error: INSTALLATION FAILED: must either provide a name or specify --generate-name

$ helm version
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
