### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by jabdoa2** [wave-k8s/wave#83]
Would it be possible to get a new release including the helm chart? Installing a helm chart from master feels wrong.

**Comment by gargath** [comment]
I'll be looking into creating a new release over the next few days.

Please note that with the migration of the repository to a dedicated Github organisation the container registry will change for all subsequent releases.

**Comment by gargath** [comment]
It's going to happen

**Comment by Ghazgkull** [comment]
Just circling through updating dependencies in my cluster and I would love a new release of this project also.

Without a release to move to, here's an example of what clients are doing in the wild:

```
   image: "quay.io/pusher/wave:56a05d780d5dad25a673055f37f674d4f2ca182a"
```

**Comment by gargath** [comment]
`v0.5.0` is finally out. Sorry for the delay in getting there.
