### ISSUE TITLE
Scope a specific configmap or secret

### ISSUE THREAD

**Issue by whitelion-github** [wave-k8s/wave#99]
Is it possible to scope a specific configmap or secret in the deployment ?

**Comment by gargath** [comment]
I assume you mean to limit Wave to just a certain `ConfigMap` / `Secret`?
That is not currently possible.

The idea behind Wave is to ensure that no matter what configuration a `Deployment` consumes, any changes to these will result in a rollout of that `Deployment`. Not needing to specifically list these means there is no chance of the watched config going out of sync with what the `Deployment` actually uses.

What is your use case for wanting to limit Wave in this way?

**Comment by whitelion-github** [comment]
We're using cert-manager and want to force a rollout when the secret containing the certificate change (new cert).
You're right, whatever configmap or secret modified, it would answer the our need.
Tks.
